### ISSUE TITLE
Devices don't show

### ISSUE THREAD

**Issue by TheGlorySaint** [aperezm85/streamdeck-tado-plugin#8]
I really would love to use your Plugin but sadly after logging in. I can't choose in the Dropdown Menu the Device or something else. My Name that I enter in die Login Dialog is displayed but not more.

I use MacOS Ventura, M1 Pro 16 " MacBook
StreamDeck Version 5.3.3(15214)
StreamDeck Version 1 Firmware 1.03.000

**Comment by aperezm85** [comment]
Hi @TheGlorySaint 
Sorry for the late replay.

Could you update to the latest StreamDeck version (6.0.2) [https://www.elgato.com/en/downloads] and try again?

If the error persist, could you test your credentials here: https://aperezm85.github.io/streamdeck-tado-plugin/ to check if there is an error with the API, please?

Thanks
Alex

**Comment by TheGlorySaint** [comment]
Hey @aperezm85 

I'on the New StreamDeck Version. I also checked the Link you Send, Screenshot is attatched. 

![image](https://user-images.githubusercontent.com/21318321/210229567-3ec42477-03f9-4657-a76e-092dd7021965.jpeg)

**Comment by aperezm85** [comment]
Did you introduced a name on the form?
Did you uninstalled the plugin and installed again?

**Comment by TheGlorySaint** [comment]
I introduced a name, i reinstalled it.
When i want to add a new Account, in the dropdown menu there is no item displayed(visible), but i can click something

**Comment by aperezm85** [comment]
Could you share a screenshot of the streamdeck, please?

**Comment by TheGlorySaint** [comment]
I hope all these Screenshots help you.

![Bildschirm­foto 2023-01-02 um 19 54 18](https://user-images.githubusercontent.com/21318321/210269723-33110c72-6511-4d42-aea7-a3ad79bda63f.png)
![Bildschirm­foto 2023-01-02 um 19 54 13](https://user-images.githubusercontent.com/21318321/210269724-f1d7d762-7d30-4294-86f0-79744dac859a.png)
![Bildschirm­foto 2023-01-02 um 19 53 19](https://user-images.githubusercontent.com/21318321/210269725-d45b02bf-592f-4ce9-8ad7-ac63ac0f3629.png)
![Bildschirm­foto 2023-01-02 um 19 53 14](https://user-images.githubusercontent.com/21318321/210269727-7d789193-5a09-4fa7-a45a-d9c55e66a6a3.png)
![Bildschirm­foto 2023-01-02 um 19 53 01](https://user-images.githubusercontent.com/21318321/210269728-7082a362-85fc-487c-924b-06ce646637ef.png)
![Bildschirm­foto 2023-01-02 um 19 52 50](https://user-images.githubusercontent.com/21318321/210269731-6ff071ae-a0a7-45d8-8b86-a7cc54225367.png)

**Comment by aperezm85** [comment]
Ok, seems like is a translation issue, for some reason is not defaulting to the English translation.
Which language is your stream deck set up?

**Comment by TheGlorySaint** [comment]
German Language Setup, but still no device showing.

**Comment by aperezm85** [comment]
ok, I just Google translated the file and uploaded into this repository. If you don't mind, before I send the update to ElGato to publish it, would you mind to follow this steps and see if is fixed?

First download the file 
https://github.com/aperezm85/streamdeck-tado-plugin/blob/master/Sources/dev.aperez.tado.sdPlugin/de.json


On your mac, close completely the streamdeck app (right click on the icon and Quit Stream Deck)
Then on Finder > Go and introduce this `~/Library/Application Support/com.elgato.StreamDeck/Plugins/dev.aperez.tado.sdPlugin`
There paste the de.json file

Open the Stream deck app and check if it shows the text on the left in German and you can see the values of the entries

Also, apologies if the translations doesn't make sense, it was a quick google translations copy and paste

**Comment by TheGlorySaint** [comment]
I got the german localization now, but at the Room Key in the drop down i can't select anything but now in Configuration it shows my created configuration.

**Comment by aperezm85** [comment]
Let's see if the API for some reason is different.
I am trying to update the html tester but I cannot do calls to the TADO Api due to CORS, so, if you have postman, could you check this 3 API calls, please?

Run postman and introduce this URL 
1- Get Auth Token
DO a POST to 
`https://auth.tado.com/oauth/token?client_id=tado-web-app&client_secret=wZaRN7rpjn3FoNyF5IFuxg9uMzYJcvOoQ8QWiIqS3hfk6gLhVlG57j5YNoZL2Rtc&grant_type=password&scope=home.user&username={YOUR EMAIL HERE}&password={YOUR PASSWORD HERE}`
Replace your email and password

Don't share this results here, if you don't mind, send them to my email (aperezm85@gmail.com)

Copy the content of the access token

2 - Get Home Id
Do a GET to 
`https://my.tado.com/api/v1/me`

and on the authorization tab, select Type Bearer Token and paste the access token for the previous result

If you don't mind, share that JSON object with me (be careful, hide your personal data from there, like email, name and username)
From that JSON, get the homeId

3 - Get the zones

Do a GET to 
`https://my.tado.com/api/v2/homes/XXXX/zones` replacing XXXX for the HOME ID from the previous call
and on the authorization tab, select Type Bearer Token and paste the access token for the previous result
and send me the JSON object to me to investigate

Thanks and sorry for all the problems

**Comment by TheGlorySaint** [comment]
I have send you an Mail with all the things you asked me for.

**Comment by aperezm85** [comment]
Thanks @TheGlorySaint  for your help.

I found that you are using an Air Conditionair product from tado. Sadly the plugin doesn't support them, yet.
I will try to find the rigth API and update the plugin.

I will keep you informed.

Thanks for your help, I will close the bug then :)
